### ISSUE TITLE
Syphon Filter (USA) (SCUS-94240) doesn't work

### ISSUE THREAD

**Issue by Keysersoze-77** [notaz/pcsx_rearmed#317]
When I start the game with the emulator under Retroarch on my Fire TV Stick 4K, the publisher's logo (989 Studios) loads, but then it takes forever for the intro cutscene to load. This also cannot be canceled and after the cutscene it takes (again) forever until the main menu loads. None of the options can be selected here and the game cannot be started.

By the way, the European version of the game runs without any problems.

**Comment by notaz** [comment]
Should be fixed now.

**Comment by Keysersoze-77** [comment]
Thank you very much! Indeed the loading times habe improved and the game loads very fast now.
Unfortunately I'm still not able to skip the intro-cutscene and choose "New game". Seems like the X-Button isn't recognized here.
I started a game on my PC and used a save state on my Fire TV stick. In the actual game the X-Button works fine. Very strange.

**Comment by notaz** [comment]
The X button works fine here on ARM (r-pi4) and PC, so no idea. I can't fix what I can't reproduce.

**Comment by Reideldm** [comment]
I don't know if it will help you at this point but I realized that if you set the cpu clock to 59 the x button works and you can play normally also works with the next tetris

**Comment by Keysersoze-77** [comment]
That worked for me. Thank you very much!
